name: Build and deploy to Codeberg Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 这个就是Permissions
enable-openid-connect: true   # 需要推送至 pages 分支

jobs:
  deploy:
    runs-on: codeberg-small
    name: Build and deploy to Codeberg Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "11"

      - name: Install Dependencies
        run: pnpm install

      - name: Build page and tools
        run: pnpm run build

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          source: ./dist
          site: https://moe520.haoqi75.cn.mt
          server: codeberg.page
          token: ${{ forge.token }}