name: Build and deploy to Codeberg Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write   # 需要推送至 pages 分支

jobs:
  deploy:
    runs-on: codeberg-medium   # 或 ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "11"

      - name: Install Dependencies
        run: pnpm install

      - name: Build page
        run: pnpm run build

      - name: Build tools
        run: pnpm run build:tools

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          directory: ./dist
          site: https://${{ forge.repository_owner }}.codeberg.page/markdown-viewer-moe/
          token: ${{ forge.token }}